dist: trusty
sudo: required
language: php

php: 
  - 7.1.9

branches:
  only:
    - master #-> Staging Server 
    - devlop #-> DevServer

# Sebelum melakukan atau eksekusi script
# Install kebutuhan OS,Ext: mod-php dll.


# Pre Excecution
# Testing dll.
before_script:

# Main Excecution
script: