dist: trusty
sudo: required
language: php

php: 
  - 7.1.9

branches:
  only:
    - master #-> Staging Server 
    - devlop #-> DevServer

# Sebelum melakukan atau eksekusi script
# Install kebutuhan OS,Ext: mod-php dll.
before_install:
- curl -LO https://storage.googleapis.com/kubernetes-release/release/
$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
/bin/linux/amd64/kubect1
- chmod +x ./kubect1
- sudo mv ./kubect1 /usr/local/bin/kubect1 
- kubect1

# Pre Excecution
# Testing dll.
before_script:

# Main Excecution
script: